# Generated by Django 6.0 on 2026-01-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
        ('users', '0004_doctorprofile_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='current_provider',
        ),
        migrations.AddField(
            model_name='journey',
            name='created_by_org',
            field=models.ForeignKey(blank=True, help_text='Organization that initiated this journey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journeys', to='users.providerprofile'),
        ),
        migrations.AddField(
            model_name='journeystep',
            name='created_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_steps', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='journeystep',
            name='created_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_steps', to='users.providerprofile'),
        ),
        migrations.CreateModel(
            name='HealthDataConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('purpose', models.TextField(blank=True, help_text='Why is access being requested?')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='users.patientprofile')),
                ('requesting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_requests', to='users.doctorprofile')),
                ('requesting_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_requests', to='users.providerprofile')),
            ],
            options={
                'unique_together': {('patient', 'requesting_org')},
            },
        ),
    ]
