# Generated by Django 6.0 on 2026-01-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_remove_journey_current_provider_and_more'),
        ('users', '0005_patientprofile_address_patientprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystep',
            name='assigned_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to='users.providerprofile'),
        ),
    ]
