# Generated by Django 6.0 on 2026-01-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockAbhaRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abha_address', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockHealthFacilityRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hfr_id', models.CharField(help_text='e.g. IN-MH-123456', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy')], max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MockHealthProfessionalRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpr_id', models.CharField(help_text='e.g. 1234-5678-9012', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
