# Generated by Django 6.0 on 2026-01-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockhealthfacilityregistry',
            name='phone_number',
            field=models.CharField(default='TEMP-PHONE', max_length=10),
            preserve_default=False,
        ),
    ]
