# Generated by Django 6.0 on 2026-01-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hpr_id',
            field=models.CharField(default='TEMP-DEFAULT', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='hfr_id',
            field=models.CharField(default='TEMP-DEFAULT', max_length=50),
            preserve_default=False,
        ),
    ]
