# Generated by Django 6.0 on 2026-01-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_doctorprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization (hospital/clinic) this doctor works at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='users.providerprofile'),
        ),
    ]
