# Generated by Django 6.0 on 2026-01-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, help_text='When doctor completed consultation', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, help_text='When doctor started consultation', null=True),
        ),
    ]
