# Generated by Django 6.0 on 2026-01-02 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
