# Generated by Django 6.0 on 2026-01-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the consultation fee has been paid'),
        ),
    ]
